name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node-version:
          - lts/-2
          - lts/-1
          - lts/*
          - latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/.yarn'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn build

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - run: corepack enable
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/.yarn'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn lint
