name: "CI"
on: [push, pull_request]
jobs:

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        yarn-version:
          - berry
        node-version:
          - 18.x
          - 20.x
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use Yarn ${{ matrix.yarn-version }}
        run: yarn set version ${{ matrix.yarn-version }}
      - name: Ensure line endings are consistent
        run: git config --global core.autocrlf input
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-test-modules-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build
        run: yarn run build
      - name: Prepare
        run: yarn run prepare

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Use Yarn 3.x
        run: yarn set version berry
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Load cache
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-lint-modules-v1-${{ hashFiles('**/yarn.lock') }}
      - name: Install dependencies
        run: yarn install --immutable
      - name: Run linter
        run: yarn run lint
