name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 23.x

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js ${{ env.DEFAULT_NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - name: Enable Corepack
        run: corepack enable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable --mode skip-build
      - name: Run ESLint
        run: yarn run lint
  test:
    name: Test
    needs: lint
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18.x
          - 20.x
          - 22.x
          - 23.x
    runs-on: ${{ matrix.os }}
    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enable Corepack
        run: corepack enable
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install --immutable
      - name: Execute unit tests
        run: yarn run test --selectProjects packages
