name: CI

on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEFAULT_NODE_VERSION: 22.x

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.DEFAULT_NODE_VERSION }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn run lint

  build:
    needs: lint
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            .yarn
            **/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
      - run: yarn install --immutable
      - run: yarn run build:ts
      - run: yarn run build:components
      - run: yarn run build:engines
